server:
  port: 7001

eureka:
  instance:
    #集群的情况
    hostname: eureka7001.com #eureka服务端实例名称
    #hostname: localhost #eureka服务端实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群的时候需要注解另一个服务的地址
      # defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  #适合在开发环境下使用
  server:
    #服务端是否开启自我保护机制 （默认true）
    enable-self-preservation: false
    #扫描失效服务的间隔时间（单位毫秒，默认是60\*1000）即60秒
    eviction-interval-timer-in-ms: 2000