server:
  port: 8002

spring:
  application:
    name: cloud-payment-service #入驻到eureka server中的名字

  datasource:
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/ezgo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456


#配置
mybatis-plus:
  #mapper位置
  mapper-locations: classpath:com.payment.mapper/*Mapper.xml
  #别名
  type-aliases-package: com.payment.entity

#  configuration:
#    #控制台日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置日志相关信息
logging:
  config: D:/IDEAWorkSpace/ezgo/prodiver-payment-8001/src/main/resources/logback.xml

#eureka-client配置
eureka:
  client:
    #表示是否将自己注册进EurekaServer
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群模式
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #单机模式
      defaultZone: http://eureka7001.com:7001/eureka/
  #根据ip注册实例
  instance:
    instance-id: payment8002
    # 显示主机的端口名称
    prefer-ip-address: true
    # Eureka注册中心（服务端）在收到客户端心跳之后，等待下一次心跳的超时时间，如果在这个时间内没有收到下次心跳，则移除该客户端。（默认90秒）
    lease-expiration-duration-in-seconds: 2
    # 客户端向注册中心发送心跳的时间间隔，（默认30秒）
    lease-renewal-interval-in-seconds: 1
#  instance:
#    ip-address: true